version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - deploy:
          name: Deploy to dev
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              ssh -o StrictHostKeyChecking=No -A $CARONAE_DEV_USER@$CARONAE_DEV_HOST -p $CARONAE_DEV_PORT "cd /var/caronae/caronae-site && sudo git fetch origin develop && sudo git reset --hard origin/develop"
            fi
      - deploy:
          name: Deploy to production
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh -o StrictHostKeyChecking=No -A $CARONAE_DEV_USER@$CARONAE_DEV_HOST -p $CARONAE_DEV_PORT "cd /var/caronae/caronae-site && sudo git fetch origin master && sudo git reset --hard origin/master"
            fi
